source: docs
paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static/uploads
  source: docs
  archetypes: archetypes
  assets: assets
  content: content
  pages: content
  publish: public
  config: ''
collections_config:
  pages:
    path: content
    output: true
    filter: strict
    parse_branch_index: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/default.md
        reorder_inputs: true
        hide_extra_inputs: true
        remove_empty_inputs: false
        remove_extra_inputs: false
        name: Page
        icon: notes
  configuration:
    path: content/configuration
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  includes:
    path: content/includes
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  installation:
    path: content/installation
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  logging-and-monitoring:
    path: content/logging-and-monitoring
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  overview:
    path: content/overview
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  troubleshooting:
    path: content/troubleshooting
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  tutorials:
    path: content/tutorials
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
data_config: {}
timezone: Etc/UTC
