source: docs
paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static/uploads
  source: docs
  archetypes: archetypes
  assets: assets
  content: content
  pages: content
  publish: public
  config: ''
collections_config:
  pages:
    path: content
    output: true
    filter: strict
    parse_branch_index: true
    description: ''
    icon: notes
    _editables:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/default.md
        reorder_inputs: true
        hide_extra_inputs: true
        remove_empty_inputs: false
        remove_extra_inputs: false
        name: Page
        icon: notes
        _editables:
        _inputs:
        _select_data:
        _structures:
  configuration:
    path: content/configuration
    output: true
    description: ''
    icon: notes
    _editables:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/default.md
        reorder_inputs: true
        hide_extra_inputs: true
        remove_empty_inputs: false
        remove_extra_inputs: false
        name: Configuration
        icon: notes
  includes:
    path: content/includes
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/includes.md
        reorder_inputs: true
        hide_extra_inputs: true
        remove_empty_inputs: false
        remove_extra_inputs: false
        name: Includes
        icon: notes
  installation:
    path: content/installation
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  logging-and-monitoring:
    path: content/logging-and-monitoring
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  overview:
    path: content/overview
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  troubleshooting:
    path: content/troubleshooting
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  tutorials:
    path: content/tutorials
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_snippets_imports:
  hugo:
    exclude:
      - hugo_youtube
      - hugo_twitter
      - hugo_vimeo
      - hugo_instagram
_snippets:
  important:
    template: hugo_paired_shortcode_named_args
    inline: false
    preview:
      text: Important
      subtext:
        - key: content_markdown
        - Important note in a callout box.
      icon: priority_high
    definitions:
      shortcode_name: important
      content_key: content_markdown
      named_args: []
  note:
    template: hugo_paired_shortcode_named_args
    inline: false
    preview:
      text: Note
      subtext:
        - key: content_markdown
        - Note in callout box.
      icon: edit_note
    definitions:
      shortcode_name: note
      content_key: content_markdown
      named_args: []
data_config: {}
timezone: Etc/UTC
commit_templates:
  - template_string: '{commit_type}: {message|trim} {breaking_change|if=breaking_change_message}'
    _inputs:
      commit_type:
        type: select
        options:
          allow_empty: true
          values:
            - feature
            - fix
            - refactor
            - update
        cascade: true
      breaking_change_message:
        type: text
        cascade: true
    extra_data:
      breaking_change: |-

        ⚠️ {breaking_change_message}